on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: adminCultisoft    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './admin'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20'    
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./admin
        file: ./admin/Dockerfile
        push: true
        tags: sergideveloper23/admin:latest  
        # Reemplaza `your-docker-repo/your-image-name` con tu repositorio e imagen Docker.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Azure Web App for Containers
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: sergideveloper23/admin:latest  
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_ADMIN }}
