# .github/workflows/deploy-backend.yml
name: Deploy Laravel Backend

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  
        extensions: mbstring, bcmath, intl, zip, curl  

    - name: Install Composer dependencies
      run: composer install --no-dev --prefer-dist --optimize-autoloader

    - name: Run Laravel Migrations
      run: php artisan migrate --force
      env:
        DB_CONNECTION: mysql  
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE  }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'backendCultisoft' 
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
